<?php

/**
 * Implements hook_admin_audit_trail_log_alter().
 *
 * Responds to admin_audit_trail events and forwards it to tide_logs otel collector.
 */
function tide_logs_admin_audit_trail_log_alter(&$log) {
  $environment = Settings::get('environment');
  if ($environment == 'ci' || $environment == 'development' || $environment == 'local') {
    return;
  }
  $channel = sprintf("admin_audit_trail_%s", $log["type"]);

  // Strip out properties that are unnecessary.
  $filtered_log = $log;
  unset(
    $filtered_log["lid"],
    $filtered_log["type"],
    $filtered_log["created"],
    $filtered_log["ip"],
    $filtered_log["ref_entity"],
  );

  // Remove markup from text fields.
  $filtered_log['description'] = preg_replace('/[\x{200B}-\x{200D}]/u', '', strip_tags($filtered_log['description']));
  $filtered_log['ref_char'] = preg_replace('/[\x{200B}-\x{200D}]/u', '', $filtered_log['ref_char']);

  // json not supported in watchdog messages. Using a comma-delimited list
  // in key:value format.
  $items = [];
  foreach ($filtered_log as $key => $value) {
    $items[] = sprintf("%s:%s", $key, $value);
  }
  $message = implode(", ", $items);

  \Drupal::logger($channel)->notice($message);
}

