# Schema for the configuration files of the tide_logs module.

tide_logs.settings:
  type: config_object
  label: 'Tide logs settings'
  mapping:
    enable:
      type: boolean
      label: 'Enabled'
    host:
      type: string
      label: 'UDPLog host'
    port:
      type: integer
      label: 'UDPLog port'
    sumologic_category:
      type: string
      label: 'Sumo Logic category'
    debug:
      type: boolean
      label: 'Show debug messages'
